import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

SENTIMENT_EMOJI = {
    "positive": "[+]",
    "negative": "[-]",
    "neutral": "[ ]",
}

def build_report(state: dict) -> str:
    ticker = state.get("ticker", "N/A")
    target_date = state.get("target_date", "N/A")
    ml_trend = state.get("ml_trend", "N/A")
    ml_confidence = state.get("ml_confidence", 0.0)
    news_sentiments = state.get("news_sentiments", "neutral")
    news_items = state.get("news_items", [])
    divergence_flag = state.get("divergence_flag", False)
    analyst_reasoning = state.get("analyst_reasoning", "")

    report = f"""# Market Analysis Report
**Ticker:** `{ticker}`
**Date:** {target_date}
---
"""

    report += f"""## Technical Signal
- **Model Prediction:** {ml_trend.upper()}
- **Confidence:** {ml_confidence * 100:.1f}%
"""

    report += f"""## News & Sentiment
- **Overall Sentiment:** {news_sentiments.upper()}
"""

    if news_items:
        report += "**Recent Headlines:**\n\n"
        for item in news_items:
            sentiment = item.get("sentiment", "neutral")
            emoji = SENTIMENT_EMOJI.get(sentiment, "[ ]")
            title = item.get("title", "No title")
            source = item.get("source", "Unknown")
            date = item.get("date", "")
            report += f"- {emoji} {title}\n"
            report += f"  - *{source}* — {date}\n\n"
    else:
        report += "*No recent news articles found.*\n\n"

    report += "---\n\n"

    if divergence_flag:
        report += f"""## Signal Divergence Detected
> Model predicts **{ml_trend.upper()}** but news sentiment is **{news_sentiments.upper()}**.
"""
        if analyst_reasoning:
            report += f"""**Analyst's Take:**
> {analyst_reasoning}
"""
        else:
            report += "*No analyst commentary available.*\n\n"
    else:
        report += """## Signals Aligned
> Model prediction and news sentiment are consistent. No divergence detected.
"""

    report += """---
## Disclaimer
*This is an automated analysis generated by Market-Agent-Ops. This does not constitute financial advice. Always do your own research before making investment decisions.*
"""
    return report

def editor_node(state: dict) -> dict:
    logger.info("[Editor] Building final report...")
    report = build_report(state)
    logger.info(f"[Editor] Report generated — {len(report)} characters")
    return {
        "final_report": report,
    }

if __name__ == "__main__":
    test_state = {
        "ticker": "RELIANCE.NS",
        "target_date": "2026-08-11",
        "ml_trend": "bullish",
        "ml_confidence": 0.85,
        "news_items": [
            {"title": "Reliance Q2 profit jumps 20%", "content": "...", "source": "Economic Times", "date": "2026-08-10", "sentiment": "positive"},
            {"title": "SEBI opens probe into Reliance accounts", "content": "...", "source": "Moneycontrol", "date": "2026-08-09", "sentiment": "negative"},
            {"title": "Markets close flat on Monday", "content": "...", "source": "Livemint", "date": "2026-08-08", "sentiment": "neutral"},
        ],
        "news_sentiments": "bearish",
        "divergence_flag": True,
        "analyst_reasoning": "Despite strong technical indicators, recent regulatory concerns may introduce short-term downside risk.",
    }
    result = editor_node(test_state)
    print(result["final_report"])